--liquibase formatted sql
--changeset Chertenkov:dev_0001
CREATE TABLE IF NOT EXISTS hotels (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description TEXT,
                       brand VARCHAR(100),
                       house_number INT,
                       street VARCHAR(255),
                       city VARCHAR(100),
                       country VARCHAR(100),
                       post_code VARCHAR(20),
                       phone VARCHAR(20),
                       email VARCHAR(100),
                       check_in VARCHAR(5),
                       check_out VARCHAR(5)
);
-- rollback DROP TABLE hotels;